// define constants
export const LOGIN_REQUEST_BEGIN = "LOGIN_REQUEST_BEGIN";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

export const CLEAR_USER_EMAIL_PWD = "CLEAR_USER_EMAIL_PWD";

export const FETCH_ENCDATA_REQUEST_BEGIN = "FETCH_ENCDATA_REQUEST_BEGIN";
export const FETCH_ENCDATA_REQUEST_SUCCESS = "FETCH_ENCDATA_REQUEST_SUCCESS";
export const FETCH_ENCDATA_REQUEST_FAILURE = "FETCH_ENCDATA_REQUEST_FAILURE";
